# Generated by Django 5.1.15 on 2026-09-07 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chore',
            options={'ordering': ['due_date', 'created_at']},
        ),
        migrations.AddField(
            model_name='chore',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
