# Generated by Django 5.1.15 on 2026-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_alter_chore_options_chore_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
