# Generated by Django 5.1.15 on 2026-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_chore_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='chore',
            name='series_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
